name: SonarQube CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: First build ide
        run: ./gradlew ide

      - name: Build with gradle
        run: ./gradlew build

      - name: Unzip SonarQube Distribution
        run: unzip ./sonar-application/build/distributions/sonar-application-25.2-SNAPSHOT.zip -d ./sonarqube

      - name: Start SonarQube
        run: ./sonarqube/sonarqube-25.2-SNAPSHOT/bin/linux-x86-64/sonar.sh start
